#端口，项目上下文根
server:
  port: 8080
  servlet:
    context-path: /
    
#配置mybatis
mybatis:
  #配置xml映射路径
  mapper-locations: classpath:mapper/*.xml
   #配置实体类的别名
  type-aliases-package: com.example.clubmanagement.entity
  configuration:
    #开启驼峰命名法
    map-underscore-to-camel-case: true
    

#配置mysql连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/club_management?useSSL=false&serverTimezone=UTC
    username: root
    password: LIUMENGYU666
    driver-class-name=com: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      auto-commit: true
      maximum-pool-size: 10
  # 文件大小 MB必须大写
# maxFileSize 是单个文件大小
# maxRequestSize是设置总上传的数据大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB

jwt:
  secret: mySecretKeyWhichIsAtLeast64CharactersLong
  expiration: 86400000  # 24 hours



      
      
